import './globals.css'
import type { Metadata } from 'next'
import Head from 'next/head'
import SessionProvider from './context/SessionContext'

export const metadata: Metadata = {
  title: 'Lesson App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <> 
      <html lang="en">
      <Head>
        <link href="https://fonts.cdnfonts.com/css/sf-pro-display" rel="stylesheet" />
      </Head> 
       <body >
        <SessionProvider>
          {children}
        </SessionProvider>
        </body>
     </html>
     </>
   
  )
}
